name = "mail-dashboard"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "mail-dashboard-db"
database_id = "efaf5558-c34d-418a-ac11-842d56bc197f"

# Environment variables
[vars]
APP_NAME = "Mail Dashboard"
ADMIN_EMAIL = "admin@yourdomain.com"
